### ISSUE TITLE
Kindly help me sort out this errors

### ISSUE THREAD

**Issue by bhushanpawar1707** [bilelomrani1/s5p-tools#5]
(base) C:\Users\bhushan.pawar\my project\me>python s5p-request.py L2_NO2_
Traceback (most recent call last):
  File "C:\Users\bhushan.pawar\my project\me\s5p-request.py", line 15, in <module>
    from s5p_tools import (bounding_box,convert_to_l3_products,get_filenames_request,request_copernicus_hub,)
  File "C:\Users\bhushan.pawar\my project\me\s5p_tools\__init__.py", line 2, in <module>
    from .preprocess import bounding_box, convert_to_l3_products
  File "C:\Users\bhushan.pawar\my project\me\s5p_tools\preprocess.py", line 6, in <module>
    import geopandas
  File "C:\Users\bhushan.pawar\Miniconda3\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "C:\Users\bhushan.pawar\Miniconda3\lib\site-packages\geopandas\_config.py", line 126, in <module>
    default_value=_default_use_pygeos(),
  File "C:\Users\bhushan.pawar\Miniconda3\lib\site-packages\geopandas\_config.py", line 112, in _default_use_pygeos
    import geopandas._compat as compat
  File "C:\Users\bhushan.pawar\Miniconda3\lib\site-packages\geopandas\_compat.py", line 202, in <module>
    import rtree  # noqa
  File "C:\Users\bhushan.pawar\Miniconda3\lib\site-packages\rtree\__init__.py", line 9, in <module>
    from .index import Rtree, Index  # noqa
  File "C:\Users\bhushan.pawar\Miniconda3\lib\site-packages\rtree\index.py", line 6, in <module>
    from . import core
  File "C:\Users\bhushan.pawar\Miniconda3\lib\site-packages\rtree\core.py", line 75, in <module>
    rt = finder.load()
  File "C:\Users\bhushan.pawar\Miniconda3\lib\site-packages\rtree\finder.py", line 67, in load
    raise OSError("could not find or load {}".format(lib_name))
OSError: could not find or load spatialindex_c-64.dll

**Comment by bilelomrani1** [comment]
Sorry for the late answer. This issue does not seem related to this project, but rather with your installation of `geopandas`. Perhaps you can take a look at [this issue](https://github.com/geopandas/geopandas/issues/1812).

**Comment by bhushanpawar1707** [comment]
Thanks dear to convey me the details , i will try to correct it ASAP
